

export const culturalEventsData = {
  "1": {
  title: "Day 1 - Opening Ceremony & Competitions",
  venue: "APSIT Campus",
  date: "TBA",
  description: "Kickstart the cultural fest with exciting opening events and competitions",
  events: [
    {
      id: 1,
      name: "Paintball",
      slug: "paintball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Turf",
      descp: "Outdoor paintball combat game.",
      description: "Outdoor paintball combat game.",
      img: "https://imgs.search.brave.com/7tOh2_NgOAnfHHmZH_Xs-osrvp-Fv_ijG4vlXcd48og/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/Z2JyaTJsNjNsbTAx/MS5qcGc_d2lkdGg9/NjQwJmNyb3A9c21h/cnQmYXV0bz13ZWJw/JnM9YTg3MTBkMGJk/NzEyZmUxODRmYjc0/Y2UxMzQ1MDI5YTU2/ZDlkZmRjMA",
      image: "https://imgs.search.brave.com/7tOh2_NgOAnfHHmZH_Xs-osrvp-Fv_ijG4vlXcd48og/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/Z2JyaTJsNjNsbTAx/MS5qcGc_d2lkdGg9/NjQwJmNyb3A9c21h/cnQmYXV0bz13ZWJw/JnM9YTg3MTBkMGJk/NzEyZmUxODRmYjc0/Y2UxMzQ1MDI5YTU2/ZDlkZmRjMA",
      registrationLink: "/register/paintball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/1",
      heads: [{ name: "Riddhesh Samadhiya", contact: "9130222873" }]
    },
    {
      id: 2,
      name: "Human Fuss Ball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "FlagPost",
      descp: "Life-size foosball game.",
      description: "Life-size foosball game.",
      img: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      registrationLink: "/register/human-foosball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/2",
      heads: [{ name: "Vikash Chuabey", contact: "9594460363" }]
    },
    {
      id: 3,
      name: "Fine Arts",
      category: "Arts",
      time: "11AM-3PM",
      venue: "Room 004",
      descp: "Art and craft competition.",
      description: "Art and craft competition.",
      img: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&auto=format&fit=crop",
      registrationLink: "/register/fine-arts",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/3",
      heads: [
        { name: "Komal Bundhate", contact: "8087674933" },
        { name: "Riddhima Khabya", contact: "9029858949" }
      ]
    },
    {
      id: 4,
      name: "Charades Games",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 005",
      descp: "Act-and-guess game.",
      description: "Act-and-guess game.",
      img: "https://imgs.search.brave.com/bu7YGIcIWombLCYZJn37pWdQCDiZ9QM-Dk3XV-qrInc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9jaGFy/YWRlcy0xLTY1NjYx/ZDE3OTc0ZmUuanBn/P3Jlc2l6ZT05ODA6/Kg",
      image: "https://imgs.search.brave.com/bu7YGIcIWombLCYZJn37pWdQCDiZ9QM-Dk3XV-qrInc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9jaGFy/YWRlcy0xLTY1NjYx/ZDE3OTc0ZmUuanBn/P3Jlc2l6ZT05ODA6/Kg",
      registrationLink: "/register/charades",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/4",
      heads: [
        { name: "Sahana Murthy", contact: "9137064826" },
        { name: "Prathamesh Patil", contact: "9518921776" }
      ]
    },
    {
      id: 5,
      name: "Karaoke",
      category: "Music",
      time: "11AM-12PM",
      venue: "Room 008",
      descp: "Singing with instrumental tracks.",
      description: "Singing with instrumental tracks.",
      img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      registrationLink: "/register/karaoke",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/5",
      heads: [{ name: "Mayuresh Sonawane", contact: "9082773125" }]
    },
    {
      id: 6,
      name: "Faculty Event",
      category: "Special",
      time: "1PM-3PM",
      venue: "Room 008",
      descp: "Special event organized for faculty.",
      description: "Special event organized for faculty.",
      img: "https://imgs.search.brave.com/Sy6x--_3cHQO5vb1lEAShbTCCR59SjVlYkfDfD7nWv8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/aG91c2VvZmV2ZW50/cy5jb20vZmlsZXMv/Y2FjaGUvbGFyZ2Uv/ZmlsZXMvZmFjdWx0/eS1jbHViLWZlZXN0/emFhbC10ZS1sZXV2/ZW4tZXZlbnRsb2Nh/dGllLWdhcmRlbi1s/b3VuZ2UtbWVpLTIw/MTktaG91c2Utb2Yt/ZXZlbnRzLTctNWQ1/ZDE2YjRiM2M3Mi5q/cGc",
      image: "https://imgs.search.brave.com/Sy6x--_3cHQO5vb1lEAShbTCCR59SjVlYkfDfD7nWv8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/aG91c2VvZmV2ZW50/cy5jb20vZmlsZXMv/Y2FjaGUvbGFyZ2Uv/ZmlsZXMvZmFjdWx0/eS1jbHViLWZlZXN0/emFhbC10ZS1sZXV2/ZW4tZXZlbnRsb2Nh/dGllLWdhcmRlbi1s/b3VuZ2UtbWVpLTIw/MTktaG91c2Utb2Yt/ZXZlbnRzLTctNWQ1/ZDE2YjRiM2M3Mi5q/cGc",
      registrationLink: null,
      participants: "Faculty",
      prize: "N/A",
      url: "/cultural/event/6",
      heads: []
    },
    
    {
      id: 8,
      name: "Doors of Fortune",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 104",
      descp: "Luck-based mystery door challenge.",
      description: "Luck-based mystery door challenge.",
      img: "https://imgs.search.brave.com/JbRvUgFZ8YD-UX4U_puSDPIYIBAqDjpq4Ik2sMkudag/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c2NyYW50b25jdWx0/dXJhbGNlbnRlci5v/cmcvY2FsZW5kYXIv/d3AtY29udGVudC91/cGxvYWRzLzIwMjUv/MDMvUk8tRXZlbnQt/Q292ZXItNC0zMDB4/MTU3LmpwZw",
      image: "https://imgs.search.brave.com/JbRvUgFZ8YD-UX4U_puSDPIYIBAqDjpq4Ik2sMkudag/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/c2NyYW50b25jdWx0/dXJhbGNlbnRlci5v/cmcvY2FsZW5kYXIv/d3AtY29udGVudC91/cGxvYWRzLzIwMjUv/MDMvUk8tRXZlbnQt/Q292ZXItNC0zMDB4/MTU3LmpwZw",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/8",
      heads: [
        { name: "Jidnyasa Alande", contact: "8828617380" },
        { name: "Hetvi Patel", contact: "7045631351" },
        { name: "Krish Shirpat", contact: "9987445344" }
      ]
    },
    {
      id: 9,
      name: "Squid Game",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 105",
      descp: "Survival-based elimination challenges.",
      description: "Survival-based elimination challenges.",
      img: "https://imgs.search.brave.com/CinmHW9Rl4fLPyrw97nmTyr5isvOmWYx2rssfkg9zCw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9leHRl/cm5hbC1wcmV2aWV3/LnJlZGQuaXQvYmxh/Y2stb3BzLTYteC1z/cXVpZC1nYW1lLWV2/ZW50LWRldGFpbHMt/djAtRFdBOUhUVVNv/cHFzWFJOMlh2aW5J/REpLY3JTSWgwTGVH/RlM2ejV0OG9Mby5q/cGc_d2lkdGg9NjQw/JmNyb3A9c21hcnQm/YXV0bz13ZWJwJnM9/MmIyZTNhMzM0NmNk/MWVkMjgzYjJkODQ3/N2UxOWZmYjk3ZGY1/YzlmMw",
      image: "https://imgs.search.brave.com/CinmHW9Rl4fLPyrw97nmTyr5isvOmWYx2rssfkg9zCw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9leHRl/cm5hbC1wcmV2aWV3/LnJlZGQuaXQvYmxh/Y2stb3BzLTYteC1z/cXVpZC1nYW1lLWV2/ZW50LWRldGFpbHMt/djAtRFdBOUhUVVNv/cHFzWFJOMlh2aW5J/REpLY3JTSWgwTGVH/RlM2ejV0OG9Mby5q/cGc_d2lkdGg9NjQw/JmNyb3A9c21hcnQm/YXV0bz13ZWJwJnM9/MmIyZTNhMzM0NmNk/MWVkMjgzYjJkODQ3/N2UxOWZmYjk3ZGY1/YzlmMw",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/9",
      heads: [
        { name: "Vedant Sawant", contact: "8446055699" },
        { name: "Anubhav Tiwari", contact: "7208510600" }
      ]
    },
    {
      id: 10,
      name: "Sack Race",
      category: "Sports",
      time: "FULL DAY",
      venue: "Room 106",
      descp: "Traditional sack race.",
      description: "Traditional sack race.",
      img: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop",
      registrationLink: "/register/sack-games",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/10",
      heads: []
    },
    {
      id: 11,
      name: "Human Ludo",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Life-size board game.",
      description: "Life-size board game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/human-ludo",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/11",
      heads: [{ name: "Rohit Prajapati", contact: "8928043313" }]
    },
    {
      id: 12,
      name: "Snake & Ladder",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Life-size snake and ladder game.",
      description: "Life-size snake and ladder game.",
      img: "https://imgs.search.brave.com/aaYpSBZIPH3L2wNgk8QdtCgnYM8vCIOhvT5J4hOpmv4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9sYXJn/ZS1vdXRkb29yLXNu/YWtlcy1sYWRkZXJz/LWdhbWUtMjkyOTk1/OTEuanBn",
      image: "https://imgs.search.brave.com/aaYpSBZIPH3L2wNgk8QdtCgnYM8vCIOhvT5J4hOpmv4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9sYXJn/ZS1vdXRkb29yLXNu/YWtlcy1sYWRkZXJz/LWdhbWUtMjkyOTk1/OTEuanBn",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/12",
      heads: [{ name: "Rohit Prajapati", contact: "8928043313" }]
    },
    {
      id: 13,
      name: "IPL Auction Round 1",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 201",
      descp: "Auction-based game where participants bid for cricket players within a fixed budget.",
      description: "Auction-based game where participants bid for cricket players within a fixed budget.",
      img: "https://imgs.search.brave.com/rCwM3A9544xoPy_iZXj6967-Ze4LiyODFmn9NtUMHXc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9saWJy/YXJ5LnNwb3J0aW5n/bmV3cy5jb20vc3R5/bGVzL2Nyb3Bfc3R5/bGVfMTZfOV9kZXNr/dG9wX3dlYnAvczMv/MjAyMy0wMi82YzQ5/YmU4MC0xNjlhLTQ2/YzctYTIwNC0yNDU4/NzI1NjFhMDdfY29t/cHJlc3NlZC5qcGcu/d2VicD9pdG9rPWYx/dm9HMGpi",
      image: "https://imgs.search.brave.com/rCwM3A9544xoPy_iZXj6967-Ze4LiyODFmn9NtUMHXc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9saWJy/YXJ5LnNwb3J0aW5n/bmV3cy5jb20vc3R5/bGVzL2Nyb3Bfc3R5/bGVfMTZfOV9kZXNr/dG9wX3dlYnAvczMv/MjAyMy0wMi82YzQ5/YmU4MC0xNjlhLTQ2/YzctYTIwNC0yNDU4/NzI1NjFhMDdfY29t/cHJlc3NlZC5qcGcu/d2VicD9pdG9rPWYx/dm9HMGpi",
      registrationLink: "/register/ipl-auction",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/13",
      heads: [
        { name: "Swayam Kale", contact: "7039432582" },
        { name: "Amol Kanojiya", contact: "8976188405" }
      ]
    },
    {
      id: 14,
      name: "Sleep Walker Arena",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Blind navigation challenge guided by team.",
      description: "Blind navigation challenge guided by team.",
      img: "https://imgs.search.brave.com/vEhCZPJcWIPODS4h70GXHY_BVPd0nCwqVTRB10iqDmc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93b3Jr/cmZ1bi5jb20vd3At/Y29udGVudC91cGxv/YWRzL1dQTC8xOTYv/dGhpbWdfYmxpbmQt/c2hhcGVzXzcwMHg0/NTAuanBn",
      image: "https://imgs.search.brave.com/vEhCZPJcWIPODS4h70GXHY_BVPd0nCwqVTRB10iqDmc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93b3Jr/cmZ1bi5jb20vd3At/Y29udGVudC91cGxv/YWRzL1dQTC8xOTYv/dGhpbWdfYmxpbmQt/c2hhcGVzXzcwMHg0/NTAuanBn",
      registrationLink: null,
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/14",
      heads: [{ name: "PRATHMESH MORE", contact: "8180919810" },
        {name: "DHANASHREE DESALE", contact: "8355973073"}
      ]
    },
    {
      id: 15,
      name: "Treasure Hunt (Round 1)",
      category: "Adventure",
      time: "11AM-3PM",
      venue: "Room 203",
      descp: "Clue-based hunt involving riddles and navigation.",
      description: "Clue-based hunt involving riddles and navigation.",
      img: "https://imgs.search.brave.com/k7J1SmsB2I7umIADH0FDkVVL6OFiYbmVDYHj_RV5icI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA3LzkyLzU4LzQ0/LzM2MF9GXzc5MjU4/NDQ4MV84dDAxQWhv/cTBTZ1JzbjdwbE5I/VlRMQ0tQT0FGSERr/VC5qcGc",
      image: "https://imgs.search.brave.com/k7J1SmsB2I7umIADH0FDkVVL6OFiYbmVDYHj_RV5icI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA3LzkyLzU4LzQ0/LzM2MF9GXzc5MjU4/NDQ4MV84dDAxQWhv/cTBTZ1JzbjdwbE5I/VlRMQ0tQT0FGSERr/VC5qcGc",
      registrationLink: "/register/treasure-hunt",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/43",
      heads: [
        { name: "Manthan Patil", contact: "9324345357" },
        { name: "Arya Hegiste", contact: "7900184769" }
      ]
    },
    {
      id: 16,
      name: "Train of Dreams",
      category: "Nostalgia",
      time: "11AM-3PM",
      venue: "Room 204",
      descp: "Journey through childhood dreams using nostalgic challenges.",
      description: "Journey through childhood dreams using nostalgic challenges.",
      img: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      registrationLink: "/register/train-of-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/16",
      heads: [
        { name: "Sumiran Pote", contact: "7021041166" },
        { name: "Samruddhi Gawali", contact: "8208189115" }
      ]
    },
    {
      id: 17,
      name: "Catch Your Dreams",
      category: "Dreams",
      time: "11AM-3PM",
      venue: "Room 205",
      descp: "Multi-level game based on dreams and ambitions.",
      description: "Multi-level game based on dreams and ambitions.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/catch-your-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/17",
      heads: [
        { name: "Nirmala Sahu", contact: "9082074614" },
        { name: "Shivam Pandey", contact: "7738818657" }
      ]
    },
    {
      id: 18,
      name: "Neon Cricket",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Room 206",
      descp: "Cricket played with neon equipment in darkness.",
      description: "Cricket played with neon equipment in darkness.",
      img: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      registrationLink: "/register/neon-cricket",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/18",
      heads: [
        { name: "Vedant Mayekar", contact: "8591432538" },
        { name: "Amey Shetye", contact: "7777020247" }
      ]
    },
    {
      id: 19,
      name: "Just Dance",
      category: "Dance",
      time: "FULL DAY",
      venue: "Room 207",
      descp: "Dance performance following on-screen choreography.",
      description: "Dance performance following on-screen choreography.",
      img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      registrationLink: "/register/just-dance",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/19",
      heads: [{ name: "Yash Madhavi ", contact: "8433621713" }]
    },
    {
      id: 20,
      name: "Andhadhun",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 209",
      descp: "Blindfold-based elimination game.",
      description: "Blindfold-based elimination game.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/andhadhun",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/20",
      heads: [
        { name: "Lavanya Bakre", contact: "9930749190" },
        { name: "Anurag Yadav", contact: "8356860168" }
      ]
    },
    {
      id: 21,
      name: "Waiting Room",
      category: "Common Area",
      time: "11AM-3PM",
      venue: "Room 210",
      descp: "Common waiting area for teams before matches.",
      description: "Common waiting area for teams before matches.",
      img: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      registrationLink: null,
      participants: "Open",
      prize: "N/A",
      url: "/cultural/event/21",
      heads: []
    },
    {
      id: 22,
      name: "Inception-The Dream Realms",
      category: "Adventure",
      time: "11AM-4PM",
      venue: "Room 211",
      descp: "Multi-layer dream-based challenge game.",
      description: "Multi-layer dream-based challenge game.",
      img: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      registrationLink: "/register/inception",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/22",
      heads: [
        { name: "Vedant Surve", contact: "9870188262" },
        { name: "Shriya Aute", contact: "965342896" },
        { name: "Vinit Rajendra Sankhala", contact: "8983880285" }
      ]
    },
    {
      id: 23,
      name: "Dream Oracle Dice",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 212",
      descp: "Dice-based random challenge game.",
      description: "Dice-based random challenge game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/dream-oracle",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/23",
      heads: [
        { name: "Pranali Sawdekar", contact: "8879099226" },
        { name: "Sanskruti Hande", contact: "9137951943" }
      ]
    },
    {
      id: 24,
      name: "Chair Games",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 213",
      descp: "Musical chairs with sabotage mechanics.",
      description: "Musical chairs with sabotage mechanics.",
      img: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      registrationLink: "/register/chair-games",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/24",
      heads: [{ name: "Kedar Meerashi", contact: "9130499409" }]
    },
    {
      id: 25,
      name: "Scatter Ball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "BCR",
      descp: "Free-for-all ball elimination game.",
      description: "Free-for-all ball elimination game.",
      img: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      registrationLink: "/register/scatter-ball",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/25",
      heads: [{ name: "Arav Palsule", contact: "9833067265" }]
    }
  ]
},
"2": {
  title: "Day 2 - Main Competitions & Cultural Events",
  venue: "APSIT Campus",
  date: "TBA",
  description: "Experience the thrill of sports, games and cultural competitions",
  events: [
    {
      id: 30,
      name: "Paintball",
      slug: "paintball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Nets",
      descp: "Outdoor paintball combat game.",
      description: "Outdoor paintball combat game.",
      img: "https://imgs.search.brave.com/7tOh2_NgOAnfHHmZH_Xs-osrvp-Fv_ijG4vlXcd48og/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/Z2JyaTJsNjNsbTAx/MS5qcGc_d2lkdGg9/NjQwJmNyb3A9c21h/cnQmYXV0bz13ZWJw/JnM9YTg3MTBkMGJk/NzEyZmUxODRmYjc0/Y2UxMzQ1MDI5YTU2/ZDlkZmRjMA",
      image: "https://imgs.search.brave.com/7tOh2_NgOAnfHHmZH_Xs-osrvp-Fv_ijG4vlXcd48og/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/Z2JyaTJsNjNsbTAx/MS5qcGc_d2lkdGg9/NjQwJmNyb3A9c21h/cnQmYXV0bz13ZWJw/JnM9YTg3MTBkMGJk/NzEyZmUxODRmYjc0/Y2UxMzQ1MDI5YTU2/ZDlkZmRjMA",
      registrationLink: "/register/paintball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/30",
      heads: [{ name: "Riddhesh Samadhiya", contact: "9130222873" }]
    },
    {
      id: 31,
      name: "Body Zorbing",
      category: "Sports",
      time: "11AM-4PM",
      venue: "FlagPost",
      descp: "Inflatable body zorbing challenge.",
      description: "Inflatable body zorbing challenge.",
      img: "https://imgs.search.brave.com/QcIgat0MNTAqrkLEPHx_irDW9nZo4bW2Njr8rXdNTMc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly81Lmlt/aW1nLmNvbS9kYXRh/NS9TRUxMRVIvRGVm/YXVsdC8yMDIyLzcv/V04vSUcvU0IvMTY4/MTExMS93aGF0c2Fw/cC1pbWFnZS0yMDIy/LTA3LTA2LWF0LTIt/MDAtMzgtcG0tNTAw/eDUwMC5qcGVn",
      image: "https://imgs.search.brave.com/QcIgat0MNTAqrkLEPHx_irDW9nZo4bW2Njr8rXdNTMc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly81Lmlt/aW1nLmNvbS9kYXRh/NS9TRUxMRVIvRGVm/YXVsdC8yMDIyLzcv/V04vSUcvU0IvMTY4/MTExMS93aGF0c2Fw/cC1pbWFnZS0yMDIy/LTA3LTA2LWF0LTIt/MDAtMzgtcG0tNTAw/eDUwMC5qcGVn",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/31",
      heads: [{ name: "Soham Patil", contact: "9137770535" }]
    },
    {
      id: 32,
      name: "Chair Games",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 004",
      descp: "Musical chairs with sabotage mechanics.",
      description: "Musical chairs with sabotage mechanics.",
      img: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      registrationLink: "/register/chair-games",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/32",
      heads: [{ name: "Kedar Mirashi", contact: "9130499409" }]
    },
    {
      id: 33,
      name: "Karaoke",
      category: "Music",
      time: "FULL DAY",
      venue: "Room 005",
      descp: "Singing with instrumental tracks.",
      description: "Singing with instrumental tracks.",
      img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      registrationLink: "/register/karaoke",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/33",
      heads: [{ name: "Mayuresh Sonawane", contact: "9082773125" }]
    },
    {
      id: 34,
      name: "Music Events",
      category: "Music",
      time: "11AM-1PM",
      venue: "Room 008",
      descp: "Musical performances and activities.",
      description: "Musical performances and activities.",
      img: "https://imgs.search.brave.com/YblnP2Vs_U6iAJ50idf8KRhKhB28SJkls2TkmTuDcPc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMucGV4ZWxzLmNv/bS9waG90b3MvMTc2/MzA2Ny9wZXhlbHMt/cGhvdG8tMTc2MzA2/Ny5qcGVnP2F1dG89/Y29tcHJlc3MmY3M9/dGlueXNyZ2ImZHBy/PTEmdz01MDA",
      image: "https://imgs.search.brave.com/YblnP2Vs_U6iAJ50idf8KRhKhB28SJkls2TkmTuDcPc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMucGV4ZWxzLmNv/bS9waG90b3MvMTc2/MzA2Ny9wZXhlbHMt/cGhvdG8tMTc2MzA2/Ny5qcGVnP2F1dG89/Y29tcHJlc3MmY3M9/dGlueXNyZ2ImZHBy/PTEmdz01MDA",
      registrationLink: null,
      participants: "Group",
      prize: "N/A",
      url: "/cultural/event/34",
      heads: []
    },
    {
      id: 35,
      slug: "mrnmrs",
      name: "MR & MRS APSIT (Round 1)",
      category: "Personality",
      time: "2PM-4PM",
      venue: "Room 008",
      descp: "Personality-based paired competition.",
      description: "Personality-based paired competition.",
      img: "https://ojus.apsit.edu.in/suits_saree.png",
      image: "https://ojus.apsit.edu.in/suits_saree.png",
      registrationLink: "/register/mr-mrs-apsit",
      participants: "Pairs",
      prize: "TBA",
      url: "/cultural/event/35",
      heads: [{ name: "Shivansh Shukla", contact: "7718992512" }]
    },
    {
      id: 36,
      name: "Horror Room",
      category: "Entertainment",
      time: "11AM-4PM",
      venue: "Room 103",
      descp: "Scare-based immersive walkthrough.",
      description: "Scare-based immersive walkthrough.",
      img: "https://imgs.search.brave.com/JPdpmvwPGcWHDxrFWMsuT3Sb0RPyDudDvOw9-U7p2Do/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuZ2VuaWFsbHku/Y29tL2dlbmlhbC5s/eS9nZW5pYWxseS90/ZW1wbGF0ZXMvYjQ1/ZWY0NDMtM2IwMC00/OTIxLTkyNjMtMTE3/YTg5ZjE0MjkxLmpw/ZWc",
      image: "https://imgs.search.brave.com/JPdpmvwPGcWHDxrFWMsuT3Sb0RPyDudDvOw9-U7p2Do/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuZ2VuaWFsbHku/Y29tL2dlbmlhbC5s/eS9nZW5pYWxseS90/ZW1wbGF0ZXMvYjQ1/ZWY0NDMtM2IwMC00/OTIxLTkyNjMtMTE3/YTg5ZjE0MjkxLmpw/ZWc",
      registrationLink: "/register/horror-room",
      participants: "Individual/Team",
      prize: "N/A",
      url: "/cultural/event/36",
      heads: [
        { name: "Nishant Rathod", contact: "9021677152" },
        { name: "Jinal Jain", contact: "9321604628" }
      ]
    },
    {
      id: 37,
      name: "Blind Volleyball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Room 104",
      descp: "Volleyball played blindfolded.",
      description: "Volleyball played blindfolded.",
      img: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&auto=format&fit=crop",
      registrationLink: "/register/blind-volleyball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/37",
      heads: [{ name: "Mahipal Singh", contact: "8369760406" }]
    },
    {
      id: 38,
      name: "Escape Room",
      category: "Puzzle",
      time: "11AM-4PM",
      venue: "Room 105 & 106",
      descp: "Puzzle-based room escape challenge.",
      description: "Puzzle-based room escape challenge.",
      img: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      registrationLink: "/register/escape-room",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/38",
      heads: [
        { name: "Shrutika Mane", contact: "7977347161" },
        { name: "Manthan Pandrekar", contact: "9082181808" }
      ]
    },
    {
      id: 39,
      name: "Human Ludo",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Life-size board game.",
      description: "Life-size board game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/human-ludo",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/39",
      heads: [{ name: "Rohit Prajapati", contact: "" }]
    },
    {
      id: 40,
      name: "Twister",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Physical flexibility game.",
      description: "Physical flexibility game.",
      img: "https://imgs.search.brave.com/R_plpSnQ7kv-G2R0t59PDzIexPamNfE62wOxlNg7RXM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9uYXRp/b25hbGV2ZW50cHJv/cy5jb20vd3AtY29u/dGVudC91cGxvYWRz/LzIwMTQvMDQvSU1H/XzU1MDAtMTYwMHg5/MDAuanBn",
      image: "https://imgs.search.brave.com/R_plpSnQ7kv-G2R0t59PDzIexPamNfE62wOxlNg7RXM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9uYXRp/b25hbGV2ZW50cHJv/cy5jb20vd3AtY29u/dGVudC91cGxvYWRz/LzIwMTQvMDQvSU1H/XzU1MDAtMTYwMHg5/MDAuanBn",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/40",
      heads: [{ name: "Rohit Prajapati", contact: "" }]
    },
    {
      id: 41,
      name: "BGMI",
      category: "Esports",
      time: "11AM-4PM",
      venue: "Room 201",
      descp: "Team-based battle royale survival game.",
      description: "Team-based battle royale survival game.",
      img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      registrationLink: "/register/bgmi",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/41",
      heads: [{ name: "Tanmay Padule", contact: "8779556101" }]
    },
    {
      id: 42,
      name: "Sleep Walker Arena",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Blind navigation challenge guided by team.",
      description: "Blind navigation challenge guided by team.",
      img: "https://imgs.search.brave.com/vEhCZPJcWIPODS4h70GXHY_BVPd0nCwqVTRB10iqDmc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93b3Jr/cmZ1bi5jb20vd3At/Y29udGVudC91cGxv/YWRzL1dQTC8xOTYv/dGhpbWdfYmxpbmQt/c2hhcGVzXzcwMHg0/NTAuanBn",
      image: "https://imgs.search.brave.com/vEhCZPJcWIPODS4h70GXHY_BVPd0nCwqVTRB10iqDmc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93b3Jr/cmZ1bi5jb20vd3At/Y29udGVudC91cGxv/YWRzL1dQTC8xOTYv/dGhpbWdfYmxpbmQt/c2hhcGVzXzcwMHg0/NTAuanBn",
      registrationLink: null,
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/42",
      heads: [
        { name: "Prathmesh More", contact: "8180919810" },
        { name: "Dhanashree Desale", contact: "8355973073" }
      ]
    },
    {
      id: 43,
      name: "Treasure Hunt (Round 2)",
      category: "Adventure",
      time: "11AM-3PM",
      venue: "Room 203",
      descp: "Clue-based hunt involving riddles and navigation.",
      description: "Clue-based hunt involving riddles and navigation.",
      img: "https://imgs.search.brave.com/k7J1SmsB2I7umIADH0FDkVVL6OFiYbmVDYHj_RV5icI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA3LzkyLzU4LzQ0/LzM2MF9GXzc5MjU4/NDQ4MV84dDAxQWhv/cTBTZ1JzbjdwbE5I/VlRMQ0tQT0FGSERr/VC5qcGc",
      image: "https://imgs.search.brave.com/k7J1SmsB2I7umIADH0FDkVVL6OFiYbmVDYHj_RV5icI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA3LzkyLzU4LzQ0/LzM2MF9GXzc5MjU4/NDQ4MV84dDAxQWhv/cTBTZ1JzbjdwbE5I/VlRMQ0tQT0FGSERr/VC5qcGc",
      registrationLink: "/register/treasure-hunt",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/43",
      heads: [
        { name: "Manthan Patil", contact: "9324345357" },
        { name: "Arya Hegiste", contact: "7900184769" }
      ]
    },
    {
      id: 44,
      name: "Train of Dreams",
      category: "Nostalgia",
      time: "11AM-3PM",
      venue: "Room 204",
      descp: "Journey through childhood dreams using nostalgic challenges.",
      description: "Journey through childhood dreams using nostalgic challenges.",
      img: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      registrationLink: "/register/train-of-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/44",
      heads: [
        { name: "Sumiran Pote", contact: "7021041166" },
        { name: "Samruddhi Gawali", contact: "8208189115" }
      ]
    },
    {
      id: 45,
      name: "Catch Your Dreams",
      category: "Dreams",
      time: "11AM-3PM",
      venue: "Room 205",
      descp: "Multi-level game based on dreams and ambitions.",
      description: "Multi-level game based on dreams and ambitions.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/catch-your-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/45",
      heads: [
        { name: "Nirmala Sahu", contact: "9082074614" },
        { name: "Shivam Pandey", contact: "7738818657" }
      ]
    },
    {
      id: 46,
      name: "Neon Cricket",
      category: "Sports",
      time: "11AM-3PM",
      venue: "Room 206",
      descp: "Cricket played with neon equipment in darkness.",
      description: "Cricket played with neon equipment in darkness.",
      img: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      registrationLink: "/register/neon-cricket",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/46",
      heads: [{ name: "Vedant Mayekar", contact: "8591432538" }]
    },
    {
      id: 47,
      name: "Just Dance",
      category: "Dance",
      time: "FULL DAY",
      venue: "Room 207",
      descp: "Dance performance following on-screen choreography.",
      description: "Dance performance following on-screen choreography.",
      img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      registrationLink: "/register/just-dance",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/47",
      heads: [{ name: "Yash Madhavi", contact: "8433621713" }]
    },
    {
      id: 48,
      name: "Andhadhun",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 209",
      descp: "Blindfold-based elimination game.",
      description: "Blindfold-based elimination game.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/andhadhun",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/48",
      heads: [
        { name: "Lavanya Bakre", contact: "9930749190" },
        { name: "Anurag Yadav", contact: "8356860168" }
      ]
    },
    {
      id: 49,
      name: "Waiting Room",
      category: "Common Area",
      time: "11AM-3PM",
      venue: "Room 210",
      descp: "Common waiting area for teams before matches.",
      description: "Common waiting area for teams before matches.",
      img: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      registrationLink: null,
      participants: "Open",
      prize: "N/A",
      url: "/cultural/event/49",
      heads: []
    },
    {
      id: 50,
      name: "Inception-The Dream Realms",
      category: "Adventure",
      time: "11AM-3PM",
      venue: "Room 211",
      descp: "Multi-layer dream-based challenge game.",
      description: "Multi-layer dream-based challenge game.",
      img: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      registrationLink: "/register/inception",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/50",
      heads: [
        { name: "Shriya Aute", contact: "9653428968" },
        { name: "Vedant Surve", contact: "9870188262" },
        { name: "Vinit Rajendra Sankhala", contact: "8983880285" }
      ]
    },
    {
      id: 51,
      name: "Dream Oracle Dice",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 212",
      descp: "Dice-based random challenge game.",
      description: "Dice-based random challenge game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/dream-oracle",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/51",
      heads: [{ name: "Pranali Sawdekar", contact: "8879099226" }]
    },
    {
      id: 52,
      name: "Mafia",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 213",
      descp: "Role-based deduction game.",
      description: "Role-based deduction game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/mafia",
      participants: "Group-based",
      prize: "TBA",
      url: "/cultural/event/52",
      heads: [
        { name: "Hastaksh Reddy", contact: "8104886727" },
        { name: "Nishit Jain", contact: "8200801599" }
      ]
    },
    {
      id: 53,
      name: "Scatter Ball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "BCR",
      descp: "Free-for-all ball elimination game.",
      description: "Free-for-all ball elimination game.",
      img: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      registrationLink: "/register/scatter-ball",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/53",
      heads: [{ name: "Arav Palsule", contact: "9833067265" }]
    },
    {
      id: 54,
      name: "Valorant",
      slug: "valorant",
      category: "Esports",
      time: "11AM-4PM",
      venue: "Lab 301",
      descp: "Tactical shooter esports event.",
      description: "Tactical shooter esports event.",
      img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      registrationLink: "/register/valorant",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/54",
      heads: [{ name: "Karan Vethody", contact: "8850106942" }]
    },
    {
      id: 55,
      name: "FIFA",
      slug: "fifa",
      category: "Esports",
      time: "11AM-4PM",
      venue: "Lab 302",
      descp: "Football simulation esports event.",
      description: "Football simulation esports event.",
      img: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&auto=format&fit=crop",
      registrationLink: "/register/fifa",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/55",
      heads: [{ name: "Soham Patil", contact: "" }]
    },
    {
      id: 56,
      name: "Fun Fair",
      category: "Entertainment",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Carnival-style stalls and games.",
      description: "Carnival-style stalls and games.",
      img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      registrationLink: "/register/fun-fair",
      participants: "Open",
      prize: "TBA",
      url: "/cultural/event/67",
      heads: [
        { name: "Riddhi Jain", contact: "9422876240" },
        { name: "Shivank Tiwari", contact: "8104796055" }
      ]
    }
  ]
},
"3": {
  title: "Day 3 - Grand Finale & Awards",
  venue: "APSIT Campus",
  date: "TBA",
  description: "Grand finale performances and award ceremony",
  events: [
    {
      id: 60,
      name: "Karaoke",
      category: "Music",
      time: "11AM-3PM",
      venue: "Room 005",
      descp: "Singing with instrumental tracks.",
      description: "Singing with instrumental tracks.",
      img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      registrationLink: "/register/karaoke",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/60",
      heads: [{ name: "Mayuresh Sonawane", contact: "9082773125" }]
    },
    {
      id: 61,
      name: "Music Event",
      category: "Music",
      time: "10AM-12:30PM",
      venue: "Room 008",
      descp: "Live music performances.",
      description: "Live music performances.",
      img: "https://imgs.search.brave.com/YblnP2Vs_U6iAJ50idf8KRhKhB28SJkls2TkmTuDcPc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMucGV4ZWxzLmNv/bS9waG90b3MvMTc2/MzA2Ny9wZXhlbHMt/cGhvdG8tMTc2MzA2/Ny5qcGVnP2F1dG89/Y29tcHJlc3MmY3M9/dGlueXNyZ2ImZHBy/PTEmdz01MDA",
      image: "https://imgs.search.brave.com/YblnP2Vs_U6iAJ50idf8KRhKhB28SJkls2TkmTuDcPc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMucGV4ZWxzLmNv/bS9waG90b3MvMTc2/MzA2Ny9wZXhlbHMt/cGhvdG8tMTc2MzA2/Ny5qcGVnP2F1dG89/Y29tcHJlc3MmY3M9/dGlueXNyZ2ImZHBy/PTEmdz01MDA",
      registrationLink: null,
      participants: "Group",
      prize: "N/A",
      url: "/cultural/event/61",
      heads: []
    },
    {
      id: 62,
      name: "Prize Distribution",
      category: "Ceremony",
      time: "1PM-2PM",
      venue: "Room 008",
      descp: "Prize distribution ceremony.",
      description: "Prize distribution ceremony.",
      img: "https://imgs.search.brave.com/pbJEyw0yEB4bCO9QtNbDAYUm36XsKX96vrwfchRzoiU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93aGF0/aXNlc3BvcnRzLnh5/ei93cC1jb250ZW50/L3VwbG9hZHMvMjAy/NS8wOC92Mi16eHFq/ay11ZGI0YS5qcGc",
      image: "https://imgs.search.brave.com/pbJEyw0yEB4bCO9QtNbDAYUm36XsKX96vrwfchRzoiU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93aGF0/aXNlc3BvcnRzLnh5/ei93cC1jb250ZW50/L3VwbG9hZHMvMjAy/NS8wOC92Mi16eHFq/ay11ZGI0YS5qcGc",
      registrationLink: null,
      participants: "All",
      prize: "N/A",
      url: "/cultural/event/62",
      heads: []
    },
    {
      id: 63,
      slug: "mrnmrs",
      name: "MR & MRS APSIT (Round 2)",
      category: "Personality",
      time: "2PM-4PM",
      venue: "Room 008",
      descp: "Final round of MR & MRS APSIT.",
      description: "Final round of MR & MRS APSIT.",
      img: "https://ojus.apsit.edu.in/suits_saree.png",
      image: "https://ojus.apsit.edu.in/suits_saree.png",
      registrationLink: "/register/mr-mrs-apsit",
      participants: "Pairs",
      prize: "TBA",
      url: "/cultural/event/63",
      heads: [{ name: "Shivansh Shukla", contact: "7718992512" }]
    },
    {
      id: 64,
      name: "Escape Room",
      category: "Puzzle",
      time: "11AM-3PM",
      venue: "Room 105 & 106",
      descp: "Puzzle-based room escape challenge.",
      description: "Puzzle-based room escape challenge.",
      img: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      registrationLink: "/register/escape-room",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/64",
      heads: [
        { name: "Shrutika Mane", contact: "7977347161" },
        { name: "Manthan Pandrekar", contact: "9082181808" }
      ]
    },
    {
      id: 65,
      name: "IPL Auction Round 2",
      category: "Games",
      time: "11AM-2PM",
      venue: "Room 112",
      descp: "Final round of IPL auction game.",
      description: "Final round of IPL auction game.",
      img: "https://imgs.search.brave.com/rCwM3A9544xoPy_iZXj6967-Ze4LiyODFmn9NtUMHXc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9saWJy/YXJ5LnNwb3J0aW5n/bmV3cy5jb20vc3R5/bGVzL2Nyb3Bfc3R5/bGVfMTZfOV9kZXNr/dG9wX3dlYnAvczMv/MjAyMy0wMi82YzQ5/YmU4MC0xNjlhLTQ2/YzctYTIwNC0yNDU4/NzI1NjFhMDdfY29t/cHJlc3NlZC5qcGcu/d2VicD9pdG9rPWYx/dm9HMGpi",
      image: "https://imgs.search.brave.com/rCwM3A9544xoPy_iZXj6967-Ze4LiyODFmn9NtUMHXc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9saWJy/YXJ5LnNwb3J0aW5n/bmV3cy5jb20vc3R5/bGVzL2Nyb3Bfc3R5/bGVfMTZfOV9kZXNr/dG9wX3dlYnAvczMv/MjAyMy0wMi82YzQ5/YmU4MC0xNjlhLTQ2/YzctYTIwNC0yNDU4/NzI1NjFhMDdfY29t/cHJlc3NlZC5qcGcu/d2VicD9pdG9rPWYx/dm9HMGpi",
      registrationLink: "/register/ipl-auction",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/65",
      heads: [
        { name: "Swayam Kale", contact: "7039432582" },
        { name: "Amul Kanojia", contact: "8976188405" }
      ]
    },
    {
      id: 66,
      name: "Debate Theme Based",
      category: "Debate",
      time: "11AM-2PM",
      venue: "Saraswati Idol",
      descp: "Theme-based debate competition.",
      description: "Theme-based debate competition.",
      img: "https://imgs.search.brave.com/tdI04KkSAE8o4I0L846No2GzDXxxFrdlHE4vcbJ-58k/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wNzEv/ODA5Lzk2Mi9zbWFs/bC9hLWdyb3VwLW9m/LXN0dWRlbnRzLXBh/cnRpY2lwYXRlcy1p/bi1hLXB1YmxpYy1z/cGVha2luZy1ldmVu/dC13aXRoLW9uZS1z/dHVkZW50LWNvbmZp/ZGVudGx5LWFkZHJl/c3NpbmctdGhlLWF1/ZGllbmNlLXdoaWxl/LW90aGVycy1saXN0/ZW4tYXR0ZW50aXZl/bHktdGhlLWF0bW9z/cGhlcmUtaXMtZm9j/dXNlZC1hbmQtc3Vw/cG9ydGl2ZS1waG90/by5qcGVn",
      image: "https://imgs.search.brave.com/tdI04KkSAE8o4I0L846No2GzDXxxFrdlHE4vcbJ-58k/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wNzEv/ODA5Lzk2Mi9zbWFs/bC9hLWdyb3VwLW9m/LXN0dWRlbnRzLXBh/cnRpY2lwYXRlcy1p/bi1hLXB1YmxpYy1z/cGVha2luZy1ldmVu/dC13aXRoLW9uZS1z/dHVkZW50LWNvbmZp/ZGVudGx5LWFkZHJl/c3NpbmctdGhlLWF1/ZGllbmNlLXdoaWxl/LW90aGVycy1saXN0/ZW4tYXR0ZW50aXZl/bHktdGhlLWF0bW9z/cGhlcmUtaXMtZm9j/dXNlZC1hbmQtc3Vw/cG9ydGl2ZS1waG90/by5qcGVn",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/66",
      heads: []
    },
    {
      id: 67,
      name: "Fun Fair",
      category: "Entertainment",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Carnival-style stalls and games.",
      description: "Carnival-style stalls and games.",
      img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      registrationLink: "/register/fun-fair",
      participants: "Open",
      prize: "TBA",
      url: "/cultural/event/67",
      heads: [
        { name: "Riddhi Jain", contact: "9422876240" },
        { name: "Shivank Tiwari", contact: "8104796055" }
      ]
    },
    {
      id: 68,
      name: "Brain Vs Body",
      category: "Challenge",
      time: "11AM-3PM",
      venue: "Room 203",
      descp: "Back-to-back mental and physical challenges.",
      description: "Back-to-back mental and physical challenges.",
      img: "https://imgs.search.brave.com/RCGvYPOgBOeMally4-yh2ZmLi_B-dq-8Vp1PvErah2I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMjE1/MDM1MDIxMy9waG90/by9zZW5pb3Itd29t/YW4taGFuZHMtZml0/LXRoZS1wdXp6bGUt/cGFydHMuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPVJ2QUxW/SlA0Njg2NDl0VlFU/Y25UdDRXZUhjeG1x/OXEtS2JXb0QzcVF1/M3M9",
      image: "https://imgs.search.brave.com/RCGvYPOgBOeMally4-yh2ZmLi_B-dq-8Vp1PvErah2I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMjE1/MDM1MDIxMy9waG90/by9zZW5pb3Itd29t/YW4taGFuZHMtZml0/LXRoZS1wdXp6bGUt/cGFydHMuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPVJ2QUxW/SlA0Njg2NDl0VlFU/Y25UdDRXZUhjeG1x/OXEtS2JXb0QzcVF1/M3M9",
      registrationLink: "/register/brain-vs-body",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/68",
      heads: [{ name: "Tanushree Gabhane", contact: "9701199394" }]
    },
    {
      id: 69,
      name: "Just Dance",
      category: "Dance",
      time: "11AM-4PM",
      venue: "Room 207",
      descp: "Dance performance following on-screen choreography.",
      description: "Dance performance following on-screen choreography.",
      img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      registrationLink: "/register/just-dance",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/69",
      heads: [{ name: "Yash Madhavi", contact: "8433621713" }]
    },
    {
      id: 70,
      name: "Waiting Room",
      category: "Common Area",
      time: "11AM-3PM",
      venue: "Room 210",
      descp: "Common waiting area for participants.",
      description: "Common waiting area for participants.",
      img: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      registrationLink: null,
      participants: "Open",
      prize: "N/A",
      url: "/cultural/event/70",
      heads: []
    },
    {
      id: 71,
      name: "Mafia",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 213",
      descp: "Role-based deduction game.",
      description: "Role-based deduction game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/mafia",
      participants: "Group-based",
      prize: "TBA",
      url: "/cultural/event/71",
      heads: [
        { name: "Hastaksh Reddy", contact: "8104886727" },
        { name: "Nishit Jain", contact: "8200801599" }
      ]
    }
  ]
}




};
