// lib/culturalData.js or data/culturalData.js
// Centralized event data for all days

export const culturalEventsData = {
  "1": {
  title: "Day 1 - Opening Ceremony & Competitions",
  venue: "APSIT Campus",
  date: "TBA",
  description: "Kickstart the cultural fest with exciting opening events and competitions",
  events: [
    {
      id: 1,
      slug: "paintball",
      name: "Paintball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Turf",
      descp: "Outdoor paintball combat game.",
      description: "Outdoor paintball combat game.",
      img: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop",
      registrationLink: "/register/paintball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/1",
      heads: [{ name: "Riddhesh Samadhiya", contact: "9130222873" }]
    },
    {
      id: 2,
      name: "Human Fuss Ball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "FlagPost",
      descp: "Life-size foosball game.",
      description: "Life-size foosball game.",
      img: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      registrationLink: "/register/human-foosball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/2",
      heads: [{ name: "Vikash Chuabey", contact: "9594460363" }]
    },
    {
      id: 3,
      name: "Fine Arts",
      category: "Arts",
      time: "11AM-3PM",
      venue: "Room 004",
      descp: "Art and craft competition.",
      description: "Art and craft competition.",
      img: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&auto=format&fit=crop",
      registrationLink: "/register/fine-arts",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/3",
      heads: [
        { name: "Komal Bundhate", contact: "8087674933" },
        { name: "Riddhima Khabya", contact: "9029858949" }
      ]
    },
    {
      id: 4,
      name: "Charades Games",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 005",
      descp: "Act-and-guess game.",
      description: "Act-and-guess game.",
      img: "https://images.unsplash.com/photo-1492684223066-dd23140edf6d?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1492684223066-dd23140edf6d?w=800&auto=format&fit=crop",
      registrationLink: "/register/charades",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/4",
      heads: [
        { name: "Sahana Murthy", contact: "9137064826" },
        { name: "Prathamesh Patil", contact: "9518921776" }
      ]
    },
    {
      id: 5,
      name: "Karaoke",
      category: "Music",
      time: "11AM-12PM",
      venue: "Room 008",
      descp: "Singing with instrumental tracks.",
      description: "Singing with instrumental tracks.",
      img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      registrationLink: "/register/karaoke",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/5",
      heads: [{ name: "Mayuresh Sonawane", contact: "9082773125" }]
    },
    {
      id: 6,
      name: "Faculty Event",
      category: "Special",
      time: "1PM-3PM",
      venue: "Room 008",
      descp: "Special event organized for faculty.",
      description: "Special event organized for faculty.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Faculty",
      prize: "N/A",
      url: "/cultural/event/6",
      heads: []
    },
    {
      id: 7,
      slug: "mrnmrs",
      name: "MR & MRS APSIT",
      category: "Personality",
      time: "2PM-4PM",
      venue: "Room 008",
      descp: "Personality-based paired competition.",
      description: "Personality-based paired competition.",
      img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
      registrationLink: "/register/mr-mrs-apsit",
      participants: "Pairs",
      prize: "TBA",
      url: "/cultural/event/7",
      heads: [{ name: "Shivansh Shukla", contact: "7718992512" }]
    },
    {
      id: 8,
      name: "Doors of Fortune",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 104",
      descp: "Luck-based mystery door challenge.",
      description: "Luck-based mystery door challenge.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/8",
      heads: [
        { name: "Jidnyasa Alande", contact: "8828617380" },
        { name: "Hetvi Patel", contact: "7045631351" },
        { name: "Krish Shirpat", contact: "9987445344" }
      ]
    },
    {
      id: 9,
      name: "Squid Game",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 105",
      descp: "Survival-based elimination challenges.",
      description: "Survival-based elimination challenges.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/9",
      heads: [
        { name: "Vedant Sawant", contact: "8446055699" },
        { name: "Anubhav Tiwari", contact: "7208510600" }
      ]
    },
    {
      id: 10,
      name: "Sack Race",
      category: "Sports",
      time: "FULL DAY",
      venue: "Room 106",
      descp: "Traditional sack race.",
      description: "Traditional sack race.",
      img: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop",
      registrationLink: "/register/sack-games",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/10",
      heads: []
    },
    {
      id: 11,
      name: "Human Ludo",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Life-size board game.",
      description: "Life-size board game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/human-ludo",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/11",
      heads: [{ name: "Rohit Prajapati", contact: "8928043313" }]
    },
    {
      id: 12,
      name: "Snake & Ladder",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Life-size snake and ladder game.",
      description: "Life-size snake and ladder game.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/12",
      heads: [{ name: "Rohit Prajapati", contact: "8928043313" }]
    },
    {
      id: 13,
      name: "IPL Auction Round 1",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 201",
      descp: "Auction-based game where participants bid for cricket players within a fixed budget.",
      description: "Auction-based game where participants bid for cricket players within a fixed budget.",
      img: "https://images.unsplash.com/photo-1553778263-73a83babcc9a?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1553778263-73a83babcc9a?w=800&auto=format&fit=crop",
      registrationLink: "/register/ipl-auction",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/13",
      heads: [
        { name: "Swayam Kale", contact: "7039432582" },
        { name: "Amol Kanojiya", contact: "8976188405" }
      ]
    },
    {
      id: 14,
      name: "Sleep Walker Arena",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Blind navigation challenge guided by team.",
      description: "Blind navigation challenge guided by team.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/14",
      heads: [{ name: "PRATHMESH MORE", contact: "8180919810" },
        {name: "DHANASHREE DESALE", contact: "8355973073"}
      ]
    },
    {
      id: 15,
      name: "Treasure Hunt",
      category: "Adventure",
      time: "11AM-4PM",
      venue: "Room 203",
      descp: "Clue-based hunt involving riddles and navigation.",
      description: "Clue-based hunt involving riddles and navigation.",
      img: "https://images.unsplash.com/photo-1533237264985-ee4c3d0b3d6c?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1533237264985-ee4c3d0b3d6c?w=800&auto=format&fit=crop",
      registrationLink: "/register/treasure-hunt",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/15",
      heads: [
        { name: "Manthan Patil", contact: "9324345357" },
        { name: "Shravani Yeola", contact: "7021441964" },
        { name: "Pushkaraj Narkhade", contact: "9920201999" }
      ]
    },
    {
      id: 16,
      name: "Train of Dreams",
      category: "Nostalgia",
      time: "11AM-3PM",
      venue: "Room 204",
      descp: "Journey through childhood dreams using nostalgic challenges.",
      description: "Journey through childhood dreams using nostalgic challenges.",
      img: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      registrationLink: "/register/train-of-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/16",
      heads: [
        { name: "Sumiran Pote", contact: "7021041166" },
        { name: "Samruddhi Gawali", contact: "8208189115" }
      ]
    },
    {
      id: 17,
      name: "Catch Your Dreams",
      category: "Dreams",
      time: "11AM-3PM",
      venue: "Room 205",
      descp: "Multi-level game based on dreams and ambitions.",
      description: "Multi-level game based on dreams and ambitions.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/catch-your-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/17",
      heads: [
        { name: "Nirmala Sahu", contact: "9082074614" },
        { name: "Shivam Pandey", contact: "7738818657" }
      ]
    },
    {
      id: 18,
      name: "Neon Cricket",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Room 206",
      descp: "Cricket played with neon equipment in darkness.",
      description: "Cricket played with neon equipment in darkness.",
      img: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      registrationLink: "/register/neon-cricket",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/18",
      heads: [
        { name: "Vedant Mayekar", contact: "8591432538" },
        { name: "Amey Shetye", contact: "7777020247" }
      ]
    },
    {
      id: 19,
      name: "Just Dance",
      category: "Dance",
      time: "FULL DAY",
      venue: "Room 207",
      descp: "Dance performance following on-screen choreography.",
      description: "Dance performance following on-screen choreography.",
      img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      registrationLink: "/register/just-dance",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/19",
      heads: [{ name: "Yash Madhavi ", contact: "8433621713" }]
    },
    {
      id: 20,
      name: "Andhadhun",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 209",
      descp: "Blindfold-based elimination game.",
      description: "Blindfold-based elimination game.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/andhadhun",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/20",
      heads: [
        { name: "Lavanya Bakre", contact: "9930749190" },
        { name: "Anurag Yadav", contact: "8356860168" }
      ]
    },
    {
      id: 21,
      name: "Waiting Room",
      category: "Common Area",
      time: "11AM-3PM",
      venue: "Room 210",
      descp: "Common waiting area for teams before matches.",
      description: "Common waiting area for teams before matches.",
      img: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      registrationLink: null,
      participants: "Open",
      prize: "N/A",
      url: "/cultural/event/21",
      heads: []
    },
    {
      id: 22,
      name: "Inception-The Dream Realms",
      category: "Adventure",
      time: "11AM-4PM",
      venue: "Room 211",
      descp: "Multi-layer dream-based challenge game.",
      description: "Multi-layer dream-based challenge game.",
      img: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      registrationLink: "/register/inception",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/22",
      heads: [
        { name: "Vedant Surve", contact: "9870188262" },
        { name: "Shriya Aute", contact: "965342896" },
        { name: "Vinit Rajendra Sankhala", contact: "8983880285" }
      ]
    },
    {
      id: 23,
      name: "Dream Oracle Dice",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 212",
      descp: "Dice-based random challenge game.",
      description: "Dice-based random challenge game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/dream-oracle",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/23",
      heads: [
        { name: "Pranali Sawdekar", contact: "8879099226" },
        { name: "Sanskruti Hande", contact: "9137951943" }
      ]
    },
    {
      id: 24,
      name: "Chair Games",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 213",
      descp: "Musical chairs with sabotage mechanics.",
      description: "Musical chairs with sabotage mechanics.",
      img: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      registrationLink: "/register/chair-games",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/24",
      heads: [{ name: "Kedar Meerashi", contact: "9130499409" }]
    },
    {
      id: 25,
      name: "Scatter Ball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "BCR",
      descp: "Free-for-all ball elimination game.",
      description: "Free-for-all ball elimination game.",
      img: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      registrationLink: "/register/scatter-ball",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/25",
      heads: [{ name: "Arav Palsule", contact: "9833067265" }]
    }
  ]
},
"2": {
  title: "Day 2 - Main Competitions & Cultural Events",
  venue: "APSIT Campus",
  date: "TBA",
  description: "Experience the thrill of sports, games and cultural competitions",
  events: [
    {
      id: 30,
      name: "Paintball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Nets",
      descp: "Outdoor paintball combat game.",
      description: "Outdoor paintball combat game.",
      img: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop",
      registrationLink: "/register/paintball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/30",
      heads: [{ name: "Riddhesh Samadhiya", contact: "9130222873" }]
    },
    {
      id: 31,
      name: "Body Zorbing",
      category: "Sports",
      time: "11AM-4PM",
      venue: "FlagPost",
      descp: "Inflatable body zorbing challenge.",
      description: "Inflatable body zorbing challenge.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/31",
      heads: [{ name: "Soham Patil", contact: "9137770535" }]
    },
    {
      id: 32,
      name: "Chair Games",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 004",
      descp: "Musical chairs with sabotage mechanics.",
      description: "Musical chairs with sabotage mechanics.",
      img: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop",
      registrationLink: "/register/chair-games",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/32",
      heads: [{ name: "Kedar Mirashi", contact: "9130499409" }]
    },
    {
      id: 33,
      name: "Karaoke",
      category: "Music",
      time: "FULL DAY",
      venue: "Room 005",
      descp: "Singing with instrumental tracks.",
      description: "Singing with instrumental tracks.",
      img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      registrationLink: "/register/karaoke",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/33",
      heads: [{ name: "Mayuresh Sonawane", contact: "9082773125" }]
    },
    {
      id: 34,
      name: "Music Events",
      category: "Music",
      time: "11AM-1PM",
      venue: "Room 008",
      descp: "Musical performances and activities.",
      description: "Musical performances and activities.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Group",
      prize: "N/A",
      url: "/cultural/event/34",
      heads: []
    },
    {
      id: 35,
      name: "MR & MRS APSIT (Round 1)",
      category: "Personality",
      time: "2PM-4PM",
      venue: "Room 008",
      descp: "Personality-based paired competition.",
      description: "Personality-based paired competition.",
      img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
      registrationLink: "/register/mr-mrs-apsit",
      participants: "Pairs",
      prize: "TBA",
      url: "/cultural/event/35",
      heads: [{ name: "Shivansh Shukla", contact: "7718992512" }]
    },
    {
      id: 36,
      name: "Horror Room",
      category: "Entertainment",
      time: "11AM-4PM",
      venue: "Room 103",
      descp: "Scare-based immersive walkthrough.",
      description: "Scare-based immersive walkthrough.",
      img: "https://images.unsplash.com/photo-1531685250784-7569952593d2?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1531685250784-7569952593d2?w=800&auto=format&fit=crop",
      registrationLink: "/register/horror-room",
      participants: "Individual/Team",
      prize: "N/A",
      url: "/cultural/event/36",
      heads: [
        { name: "Nishant Rathod", contact: "9021677152" },
        { name: "Jinal Jain", contact: "9321604628" }
      ]
    },
    {
      id: 37,
      name: "Blind Volleyball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "Room 104",
      descp: "Volleyball played blindfolded.",
      description: "Volleyball played blindfolded.",
      img: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&auto=format&fit=crop",
      registrationLink: "/register/blind-volleyball",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/37",
      heads: [{ name: "Mahipal Singh", contact: "8369760406" }]
    },
    {
      id: 38,
      name: "Escape Room",
      category: "Puzzle",
      time: "11AM-4PM",
      venue: "Room 105 & 106",
      descp: "Puzzle-based room escape challenge.",
      description: "Puzzle-based room escape challenge.",
      img: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      registrationLink: "/register/escape-room",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/38",
      heads: [
        { name: "Shrutika Mane", contact: "7977347161" },
        { name: "Manthan Pandrekar", contact: "9082181808" }
      ]
    },
    {
      id: 39,
      name: "Human Ludo",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Life-size board game.",
      description: "Life-size board game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/human-ludo",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/39",
      heads: [{ name: "Rohit Prajapati", contact: "" }]
    },
    {
      id: 40,
      name: "Twister",
      category: "Games",
      time: "11AM-3PM",
      venue: "Saraswati Idol",
      descp: "Physical flexibility game.",
      description: "Physical flexibility game.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/40",
      heads: [{ name: "Rohit Prajapati", contact: "" }]
    },
    {
      id: 41,
      name: "BGMI",
      category: "Esports",
      time: "11AM-4PM",
      venue: "Room 201",
      descp: "Team-based battle royale survival game.",
      description: "Team-based battle royale survival game.",
      img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      registrationLink: "/register/bgmi",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/41",
      heads: [{ name: "Tanmay Padule", contact: "8779556101" }]
    },
    {
      id: 42,
      name: "Sleep Walker Arena",
      category: "Games",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Blind navigation challenge guided by team.",
      description: "Blind navigation challenge guided by team.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/42",
      heads: [
        { name: "Prathmesh More", contact: "8180919810" },
        { name: "Dhanashree Desale", contact: "8355973073" }
      ]
    },
    {
      id: 43,
      name: "Treasure Hunt (Round 2)",
      category: "Adventure",
      time: "11AM-3PM",
      venue: "Room 203",
      descp: "Clue-based hunt involving riddles and navigation.",
      description: "Clue-based hunt involving riddles and navigation.",
      img: "https://images.unsplash.com/photo-1533237264985-ee4c3d0b3d6c?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1533237264985-ee4c3d0b3d6c?w=800&auto=format&fit=crop",
      registrationLink: "/register/treasure-hunt",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/43",
      heads: [
        { name: "Manthan Patil", contact: "9324345357" },
        { name: "Arya Hegiste", contact: "7900184769" }
      ]
    },
    {
      id: 44,
      name: "Train of Dreams",
      category: "Nostalgia",
      time: "11AM-3PM",
      venue: "Room 204",
      descp: "Journey through childhood dreams using nostalgic challenges.",
      description: "Journey through childhood dreams using nostalgic challenges.",
      img: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1521939094609-93aba1af40d7?w=800&auto=format&fit=crop",
      registrationLink: "/register/train-of-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/44",
      heads: [
        { name: "Sumiran Pote", contact: "7021041166" },
        { name: "Samruddhi Gawali", contact: "8208189115" }
      ]
    },
    {
      id: 45,
      name: "Catch Your Dreams",
      category: "Dreams",
      time: "11AM-3PM",
      venue: "Room 205",
      descp: "Multi-level game based on dreams and ambitions.",
      description: "Multi-level game based on dreams and ambitions.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/catch-your-dreams",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/45",
      heads: [
        { name: "Nirmala Sahu", contact: "9082074614" },
        { name: "Shivam Pandey", contact: "7738818657" }
      ]
    },
    {
      id: 46,
      name: "Neon Cricket",
      category: "Sports",
      time: "11AM-3PM",
      venue: "Room 206",
      descp: "Cricket played with neon equipment in darkness.",
      description: "Cricket played with neon equipment in darkness.",
      img: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop",
      registrationLink: "/register/neon-cricket",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/46",
      heads: [{ name: "Vedant Mayekar", contact: "8591432538" }]
    },
    {
      id: 47,
      name: "Just Dance",
      category: "Dance",
      time: "FULL DAY",
      venue: "Room 207",
      descp: "Dance performance following on-screen choreography.",
      description: "Dance performance following on-screen choreography.",
      img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      registrationLink: "/register/just-dance",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/47",
      heads: [{ name: "Yash Madhavi", contact: "8433621713" }]
    },
    {
      id: 48,
      name: "Andhadhun",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 209",
      descp: "Blindfold-based elimination game.",
      description: "Blindfold-based elimination game.",
      img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
      registrationLink: "/register/andhadhun",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/48",
      heads: [
        { name: "Lavanya Bakre", contact: "9930749190" },
        { name: "Anurag Yadav", contact: "8356860168" }
      ]
    },
    {
      id: 49,
      name: "Waiting Room",
      category: "Common Area",
      time: "11AM-3PM",
      venue: "Room 210",
      descp: "Common waiting area for teams before matches.",
      description: "Common waiting area for teams before matches.",
      img: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      registrationLink: null,
      participants: "Open",
      prize: "N/A",
      url: "/cultural/event/49",
      heads: []
    },
    {
      id: 50,
      name: "Inception-The Dream Realms",
      category: "Adventure",
      time: "11AM-3PM",
      venue: "Room 211",
      descp: "Multi-layer dream-based challenge game.",
      description: "Multi-layer dream-based challenge game.",
      img: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop",
      registrationLink: "/register/inception",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/50",
      heads: [
        { name: "Shriya Aute", contact: "9653428968" },
        { name: "Vedant Surve", contact: "9870188262" },
        { name: "Vinit Rajendra Sankhala", contact: "8983880285" }
      ]
    },
    {
      id: 51,
      name: "Dream Oracle Dice",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 212",
      descp: "Dice-based random challenge game.",
      description: "Dice-based random challenge game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/dream-oracle",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/51",
      heads: [{ name: "Pranali Sawdekar", contact: "8879099226" }]
    },
    {
      id: 52,
      name: "Mafia",
      category: "Games",
      time: "11AM-4PM",
      venue: "Room 213",
      descp: "Role-based deduction game.",
      description: "Role-based deduction game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/mafia",
      participants: "Group-based",
      prize: "TBA",
      url: "/cultural/event/52",
      heads: [
        { name: "Hastaksh Reddy", contact: "8104886727" },
        { name: "Nishit Jain", contact: "8200801599" }
      ]
    },
    {
      id: 53,
      name: "Scatter Ball",
      category: "Sports",
      time: "11AM-4PM",
      venue: "BCR",
      descp: "Free-for-all ball elimination game.",
      description: "Free-for-all ball elimination game.",
      img: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&auto=format&fit=crop",
      registrationLink: "/register/scatter-ball",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/53",
      heads: [{ name: "Arav Palsule", contact: "9833067265" }]
    },
    {
      id: 54,
      slug: "valorant",
      name: "Valorant",
      category: "Esports",
      time: "11AM-4PM",
      venue: "Lab 301",
      descp: "Tactical shooter esports event.",
      description: "Tactical shooter esports event.",
      img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop",
      registrationLink: "/register/valorant",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/54",
      heads: [{ name: "Karan Vethody", contact: "8850106942" }]
    },
    {
      id: 55,
      slug: "fifa",
      name: "FIFA",
      category: "Esports",
      time: "11AM-4PM",
      venue: "Lab 302",
      descp: "Football simulation esports event.",
      description: "Football simulation esports event.",
      img: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&auto=format&fit=crop",
      registrationLink: "/register/fifa",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/55",
      heads: [{ name: "Soham Patil", contact: "" }]
    }
  ]
},
"3": {
  title: "Day 3 - Grand Finale & Awards",
  venue: "APSIT Campus",
  date: "TBA",
  description: "Grand finale performances and award ceremony",
  events: [
    {
      id: 60,
      name: "Karaoke",
      category: "Music",
      time: "11AM-3PM",
      venue: "Room 005",
      descp: "Singing with instrumental tracks.",
      description: "Singing with instrumental tracks.",
      img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
      registrationLink: "/register/karaoke",
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/60",
      heads: [{ name: "Mayuresh Sonawane", contact: "9082773125" }]
    },
    {
      id: 61,
      name: "Music Event",
      category: "Music",
      time: "10AM-12:30PM",
      venue: "Room 008",
      descp: "Live music performances.",
      description: "Live music performances.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Group",
      prize: "N/A",
      url: "/cultural/event/61",
      heads: []
    },
    {
      id: 62,
      name: "Prize Distribution",
      category: "Ceremony",
      time: "1PM-2PM",
      venue: "Room 008",
      descp: "Prize distribution ceremony.",
      description: "Prize distribution ceremony.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "All",
      prize: "N/A",
      url: "/cultural/event/62",
      heads: []
    },
    {
      id: 63,
      name: "MR & MRS APSIT (Round 2)",
      category: "Personality",
      time: "2PM-4PM",
      venue: "Room 008",
      descp: "Final round of MR & MRS APSIT.",
      description: "Final round of MR & MRS APSIT.",
      img: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
      registrationLink: "/register/mr-mrs-apsit",
      participants: "Pairs",
      prize: "TBA",
      url: "/cultural/event/63",
      heads: [{ name: "Shivansh Shukla", contact: "7718992512" }]
    },
    {
      id: 64,
      name: "Escape Room",
      category: "Puzzle",
      time: "11AM-3PM",
      venue: "Room 105 & 106",
      descp: "Puzzle-based room escape challenge.",
      description: "Puzzle-based room escape challenge.",
      img: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800&auto=format&fit=crop",
      registrationLink: "/register/escape-room",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/64",
      heads: [
        { name: "Shrutika Mane", contact: "7977347161" },
        { name: "Manthan Pandrekar", contact: "9082181808" }
      ]
    },
    {
      id: 65,
      name: "IPL Auction Round 2",
      category: "Games",
      time: "11AM-2PM",
      venue: "Room 112",
      descp: "Final round of IPL auction game.",
      description: "Final round of IPL auction game.",
      img: "https://images.unsplash.com/photo-1553778263-73a83babcc9a?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1553778263-73a83babcc9a?w=800&auto=format&fit=crop",
      registrationLink: "/register/ipl-auction",
      participants: "Team-based",
      prize: "TBA",
      url: "/cultural/event/65",
      heads: [
        { name: "Swayam Kale", contact: "7039432582" },
        { name: "Amul Kanojia", contact: "8976188405" }
      ]
    },
    {
      id: 66,
      name: "Debate Theme Based",
      category: "Debate",
      time: "11AM-2PM",
      venue: "Saraswati Idol",
      descp: "Theme-based debate competition.",
      description: "Theme-based debate competition.",
      img: "",
      image: "",
      registrationLink: null,
      participants: "Individual",
      prize: "TBA",
      url: "/cultural/event/66",
      heads: []
    },
    {
      id: 67,
      name: "Fun Fair",
      category: "Entertainment",
      time: "FULL DAY",
      venue: "Room 202",
      descp: "Carnival-style stalls and games.",
      description: "Carnival-style stalls and games.",
      img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
      registrationLink: "/register/fun-fair",
      participants: "Open",
      prize: "TBA",
      url: "/cultural/event/67",
      heads: [
        { name: "Riddhi Jain", contact: "9422876240" },
        { name: "Shivank Tiwari", contact: "8104796055" }
      ]
    },
    {
      id: 68,
      name: "Brain Vs Body",
      category: "Challenge",
      time: "11AM-3PM",
      venue: "Room 203",
      descp: "Back-to-back mental and physical challenges.",
      description: "Back-to-back mental and physical challenges.",
      img: "https://images.unsplash.com/photo-1519452639340-94f8236f78c8?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1519452639340-94f8236f78c8?w=800&auto=format&fit=crop",
      registrationLink: "/register/brain-vs-body",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/68",
      heads: [{ name: "Tanushree Gabhane", contact: "9701199394" }]
    },
    {
      id: 69,
      name: "Just Dance",
      category: "Dance",
      time: "11AM-4PM",
      venue: "Room 207",
      descp: "Dance performance following on-screen choreography.",
      description: "Dance performance following on-screen choreography.",
      img: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
      registrationLink: "/register/just-dance",
      participants: "Individual/Team",
      prize: "TBA",
      url: "/cultural/event/69",
      heads: [{ name: "Yash Madhavi", contact: "8433621713" }]
    },
    {
      id: 70,
      name: "Waiting Room",
      category: "Common Area",
      time: "11AM-3PM",
      venue: "Room 210",
      descp: "Common waiting area for participants.",
      description: "Common waiting area for participants.",
      img: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
      registrationLink: null,
      participants: "Open",
      prize: "N/A",
      url: "/cultural/event/70",
      heads: []
    },
    {
      id: 71,
      name: "Mafia",
      category: "Games",
      time: "11AM-3PM",
      venue: "Room 213",
      descp: "Role-based deduction game.",
      description: "Role-based deduction game.",
      img: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop",
      registrationLink: "/register/mafia",
      participants: "Group-based",
      prize: "TBA",
      url: "/cultural/event/71",
      heads: [
        { name: "Hastaksh Reddy", contact: "8104886727" },
        { name: "Nishit Jain", contact: "8200801599" }
      ]
    }
  ]
}




};